return {
	Inventory		= {
		CrewMembers		= {};
		Beli			= 0;
		Extol			= 0;
		Bounty			= 0;
		Reputation		= 0;
	};
	Progress		= {
		Character		= {Level = 0; XP = 0;};
		Strength		= {Level = 0; XP = 0;};
		Sword			= {Level = 0; XP = 0;};
		Fruit			= {Level = 0; XP = 0;};
		Haki			= {Level = 0; XP = 0;};
	};
	CrewProfile		= {};
	QuestProfile	= {};
	Equipped		= {};
	Passives		= {};
	Race			= 0;
	Fruit			= "";
	Spawn			= "";
	Style			= "";

	_P				= {};
}